"""empty message

Revision ID: 02a9b8e182aa
Revises: 
Create Date: 2019-05-30 17:50:34.213712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a9b8e182aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nome_bar', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nome_bar'), 'user', ['nome_bar'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primo_piatto', sa.JSON(), nullable=True),
    sa.Column('secondo_piatto', sa.JSON(), nullable=True),
    sa.Column('contorno', sa.JSON(), nullable=True),
    sa.Column('altro', sa.JSON(), nullable=True),
    sa.Column('orario_apertura', sa.String(length=128), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('nome_food', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['nome_food'], ['user.nome_bar'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_data'), 'food', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_data'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_nome_bar'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
